table 'Target Scale'
	lineageTag: ba26fcc6-4ee2-425d-a873-e16e473f3533

	measure 'Target Scale Value' = SELECTEDVALUE('Target Scale'[Target Scale], 1)
		lineageTag: 9b1578c5-3388-47cf-b938-f036179215bd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Target Scale'
		lineageTag: c6119f3c-fcd0-4bfe-b6ae-82584d889256
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata = {"version":0}

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Target Scale' = calculated
		mode: import
		source = GENERATESERIES(0.3, 1.5, 0.05)

	annotation PBI_Id = b50ddaafb7204265870d28bc0fa6c0c8

